# Configura a URL base do servidor Ollama
quarkus.langchain4j.ollama.base-url=http://localhost:11434/

# Define o ID do modelo de chat Ollama a ser usado
quarkus.langchain4j.ollama.chat-model.model-id=gpt-oss:20b

# Define um tempo limite de 60 segundos para as solicitações ao modelo Ollama
quarkus.langchain4j.ollama.timeout=60s

# Configura o caminho para os arquivos de RAG (Retrieval-Augmented Generation)
quarkus.langchain4j.easy-rag.path=src/main/resources/rag