# Configura a URL base do servidor Ollama
quarkus.langchain4j.ollama.base-url=http://localhost:11434/

# Define o ID do modelo de chat Ollama a ser usado
quarkus.langchain4j.ollama.chat-model.model-id=gpt-oss:20b

# Define um tempo limite de 60 segundos para as solicitações ao modelo Ollama
quarkus.langchain4j.ollama.timeout=60s

# Define o ID do modelo de embedding Ollama a ser usado
quarkus.langchain4j.ollama.embedding-model.model-id=nomic-embed-text

# Configurações do PostgreSQL com pgvector
# Habilita a extensão pgvector no PostgreSQL
quarkus.langchain4j.pgvector.register-vector-pg-extension=true
# Define a dimensão dos vetores de embedding (neste caso, 768)
quarkus.langchain4j.pgvector.dimension=768
# Define o nome da tabela no PostgreSQL onde os embeddings serão armazenados
quarkus.langchain4j.pgvector.table=travel_embeddings
# Define se a tabela de embeddings deve ser excluída antes de ser criada (true para excluir, false para manter)
quarkus.langchain4j.pgvector.drop-table-first=true

# Configurações de log para depuração
quarkus.langchain4j.log-requests=true
quarkus.langchain4j.log-responses=true
#quarkus.log.category."dev.langchain4j".level=DEBUG
#quarkus.log.category."io.quarkiverse.langchain4j".level=DEBUG
#quarkus.log.category."io.quarkiverse.langchain4j.ollama".level=DEBUG
#quarkus.log.category."io.quarkiverse.langchain4j.ollama.OllamaRestApi".level=DEBUG