package dev.ia;

import io.quarkiverse.langchain4j.RegisterAiService;

// This interface is used to register the TravelAgentAssistant service with the AI framework.
@RegisterAiService
public interface TravelAgentAssistant {

    /**
     * This method takes user input as a string and returns a response from the AI assistant.
     * @param userInput The input provided by the user.
     * @return A string response generated by the AI assistant based on the user input.
     */
    String chat(String userInput);
}
